config/routes.rb
Rails.application.routes.draw do

    root 'startups#index'

    resources :startups do
      resources :comments
    end

    devise_for :users, controllers: {
     omniauth_callbacks: 'users/omniauth_callbacks'
     }

    resources :termes

    resources :users, only: %i[show index]

    resources :relationships, only: [:create, :destroy]

    resources :favorites, only: [:create, :destroy]

    resources :conversations do
      resources :messages
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :startup
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_startup, only: %i[create edit update destroy]
  before_action :login_check, only: %i[create edit destroy]
  def create
    @comment = @startup.comments.build(comment_params)
    @comment.user_id = current_user.id
    respond_to do |format|
      if @startup.save
        format.js { render :index }
      else
        format.html { redirect_to startup_path(@startup), notice: "Couldn't post..." }
      end
    end
  end

  def edit
    @comment = @startup.comments.find(params[:id])
    respond_to do |format|
      flash.now[:notice] = 'modifier le commentaires'
      format.js { render :edit }
    end
  end

  def update
    @comment = @startup.comments.find(params[:id])
    respond_to do |format|
      if @comment.update(comment_params)
        flash.now[:notice] = 'Commentaire mis a jour'
        format.js { render :index }
      else
        flash.now[:notice] = 'commentaire non mis à jour'
        format.js { render :edit_error }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      flash.now[:notice] = 'Comment deleted'
      format.js { render :index }
    end
 end

  private

  def comment_params
    params.require(:comment).permit(:startup_id, :content)
  end

  def set_startup
    @startup = Startup.find(params[:startup_id])
  end

  def login_check
    unless user_signed_in?
      redirect_to new_user_session_path, notice: 'you are not login, please login or create new accompt'
    end
  end
end

app/views/comments/_edit.html.erb
<%= form_with(model: [@startup, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %>undefined</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.text_area :content, id: "comment_content_#{@starup}" %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: [startup, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %>undefined</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="form-group col-sm-10">
      <%= form.text_area :content,class:"form-control", placeholder:'Give your opinion on this startup here '%>
    </div>
      <div class="col-sm-2">
        <%= form.submit 'comment',:class=>"btn btn-outline-info my-2 my-sm-0" %>
      </div>
    </div>
<% end %>

app/views/comments/_index.html.erb
  <% comments.each do |comment| %>
      <% if comment.id.present? %>
      <div class="comment-content" id ="this_comment_<%= comment.id %>"></div>
        <div class="card">
           <div class="card-header">
             <strong><%= image_tag comment.user.avatar_thumbnail,style: 'height:5%;width:5%;'%> <%= link_to "#{comment.user.name }", user_path(comment.user.id) %></strong><br>
            </div>
            <div class="card-body">
            <p><%= comment.content %></p>
              <% if user_signed_in? %>
                 <% if comment.user_id == current_user.id %>
                  <small><%= link_to "edit", edit_startup_comment_path(@startup, comment), remote: true %></small>
                  |<small><%= link_to "delete", startup_comment_path(comment.startup_id, comment.id), method: :delete, remote: true %></small>
                 <% end %>
                <% end %>
          </div>
            <% end %>
          <% end %>
        </div>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/edit.js.erb
$("#this_comment_<%= @comment.id %>").replaceWith("<%= j render 'comments/edit', startup: @startup, comment: @comment %>");

app/views/comments/index.js.erb
$('#comments_area').html("<%= j(render 'comments/index', { comments: @comment.startup.comments, startup: @comment.startup }) %>")
$("textarea").val('')