config/routes.rb
Rails.application.routes.draw do

    root 'startups#index'

    resources :startups do
      resources :comments
    end

    devise_for :users, controllers: {
     omniauth_callbacks: 'users/omniauth_callbacks'
     }

    resources :termes

    resources :users, only: %i[show index]

    resources :relationships, only: [:create, :destroy]

    resources :favorites, only: [:create, :destroy]

    resources :conversations do
      resources :messages
    end
end

app/models/startup.rb
class Startup < ApplicationRecord
  mount_uploader :logo, LogoUploader
  mount_uploader :banner, BannerUploader

  validates :name, presence:true, uniqueness: true,  null:false
  validates :resume, presence:true, null:false, length:{minimum: 150}
  validates :contact, presence:true, null:false
  validates :adresse, presence:true, null:false
  validates :sector_of_business, presence:true, null:false
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  has_many :comments, dependent: :destroy
  enum sector_of_business: %i[agriculture it education transport tourism public_service trade]

  belongs_to :user


  def logo_thumbnail
    if logo.present?
      logo.url
    else
      '/default_logo.png'
    end
  end

  def banner_thumbnail
    if banner.present?
      banner.url
    else
      '/banner.gif'
    end
  end

  def description_thumbnail
    if video.present?
      video
    else
      "https://www.youtube.com/watch?v=NGi5ontIT3w"
    end
  end
end

app/controllers/startups_controller.rb
class StartupsController < ApplicationController
 before_action :authenticate_user!, only: %i[create new edit update destroy]
 before_action :set_startup, only: %i[show edit update destroy]
 before_action :login_check, only: %i[new edit destroy]
 before_action :user_check, only: %i[edit destroy]
 before_action :startup_check, only: %i[new create]



 def index
if params[:name]
   @startups = Startup.where(["name LIKE ?", "%#{params[:name]}%"]).page(params[:page]).per(10)
 else
   @startups = Startup.all.order(name: :ASC).page(params[:page]).per(10)
 end
   @user = User.all
 end

 def new
   @user = User.all
   @startup = Startup.new
 end

 def create
   @startup = current_user.startups.build(startup_params)
   if @startup.save
     StartupMailer.startup_mail(@startup).deliver
     flash[:success] = I18n.t('startup.controller.create_startup')
     redirect_to user_path(current_user.id)
   else
     render :new
 end
end

 def show
   @favorite = @startup.favorites.find_by(startup_id: @startup.id)
   @comments = @startup.comments
   @comment = @startup.comments.build
 end

 def edit; end

 def update
   if @startup.update(startup_params)
     flash[:success] = I18n.t('startup.controller.update')
     redirect_to startup_path(@startup.id)
   else
     render :edit
   end
 end

 def destroy
   @startup.destroy
   flash[:success] = I18n.t('startup.controller.destroy')
   redirect_to startups_path
 end

 def terms; end

 private

 def startup_params
   params.require(:startup).permit(:name, :resume, :contact,
                                   :video,
                                   :trade_registre,
                                   :sector_of_business,
                                   :adresse,
                                   :banner, :banner_cache,
                                   :logo, :banner_cache)
 end

 def set_startup
   @startup = Startup.find(params[:id])
 end

 def user_check
   redirect_to startups_path,  flash[:success] = I18n.t('startup.controller.user_check_error') unless current_user.id == @startup.user_id
 end


 def login_check
   unless user_signed_in?
     redirect_to new_user_registration_path, flash[:success] = I18n.t('startup.controller.login_check_error')
   end
 end

 def startup_check
   redirect_to startups_path,  flash[:success] = I18n.t('startup.controller.startup_check_error') unless current_user.startups.empty?
 end

end

app/helpers/startups_helper.rb
module StartupsHelper
end

app/views/startups/_favorites.html.erb
<span id="favorites">
  <% if user_signed_in? %>
    <% unless @startup.user_id == current_user.id %>
      <% if current_user.favorites.pluck(:startup_id).include? @startup.id%>
        <span class="badge badge-success"> you're promoted this startup</span>
      <% else %>
      <%= link_to 'PROMOTE THIS STARTUP', favorites_path(startup_id: @startup.id),  method: :post, class:" addpromote btn btn-sm btn-danger"%>
       <% end %>
     <% end %>
   <% end %>
</span>

app/views/startups/_footer.html.erb
<footer class="class="main-footer"">
        <div class="container float-right d-none d-sm-inline">
          <p><strong>Licence</strong> : <a href="https://africasamurai.com/" class="text)success">AFRICA SAMURAI CONSULTING</a></p>
      </div>
    </footer>

app/views/startups/_form.html.erb
<div class="container">
  <div id="error_explanation">
      <% if @startup.errors.any? %>
      <h2>
        <%= pluralize(@startup.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @startup.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

<div class="field">

<%= form_with(model:@startup,local: true) do |form| %>
      <div class="row">
        <div class="col-md-3">
          startup name<br>
          <%= form.text_field :name %><br>
        </div>
        <div class="col-md-3">
          contact <br>
          <%= form.text_field :contact %>
        </div>
        <div class="col-md-3">
          trade_registre <br>
          <%= form.text_field :trade_registre %><br>
        </div>
        <div class="col-md-3">
          adresse <br>
          <%= form.text_field :adresse %> <br>
        </div>
      </div>
      <hr>
      resume<br>
      <small>Make a description of your startup in minimum 150 characters:
         remember to talk about the impact of your solution.</small>
      <%= form.text_area :resume, class:"form-control" %>
      <br>
      sector_of_business <br>
      <%= form.select(:sector_of_business, {agriculture: 'agriculture', it: 'it', education: 'education', transport: 'transport', tourism: 'tourism', public_service: 'public_service', trade: 'trade'}) %> <br>
      <hr>
      <div class="row">
        <div class="col-md-4">
          your logo <br>
          <small>for your logo to be displayed well, choose an image in png or
            jpg format with a size of 330px *80 px.
            your logo is representing you. Take care of it !</small><br>
          <%= form.file_field :logo,class:"btn btn-sm btn-light" %>
          <br>
        </div>
        <div class="col-md-4">
          barnner <br>
          <small>for your banner to be displayed well, choose an image in png or
            jpg format with a size of 1200px *500 px.
            your banner is can détail your activity. Take care of it !</small> <br>
          <%= form.file_field :banner,class:"btn btn-sm btn-light" %>
          <%= form.hidden_field :banner_cache %>
          <br>
        </div>
        <div class="col-md-4">
          description video <br>
          <small>It is always more impactful to present your
            company by staging it in a video.
          you can add your video in youtub and past link here</small> <br>
          <%= form.text_field :video %>
          <br>
        </div>
      </div>
    <br>
      <div class="actions">
        <%= form.submit "create startup" ,class:"btn btn-sm btn-success" %>
      </div>
  <% end %>
  <br>
  <%= link_to "Back", :back ,class:"text-success"%>
</div>
<br>

app/views/startups/_search.html.erb
<div class="form-inline">
  <%= form_with(url: startups_path, method: :get, local: true) do |f|%>
    <%= f.text_field :name , class:"form-control mr-sm-2", placeholder: "search startup by name"%>
    <%= f.submit'search', class:"btn btn-outline-success my-2 my-sm-0"%><br>
    <span> <%= link_to "Clear search",root_path %></span>
  <% end %>
</div>

app/views/startups/edit.html.erb
<div class="field">
  <%= render 'form' %>
</div>

app/views/startups/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 col-lg-12">
      <%= render 'users/wellcome' %>
      <div class="col-md-12 col-lg-12">
        <%= render 'startups/search' %>
        <div class="offset-10 text-success">
          <%= Startup.all.count %> startups published
        </div>
      </div>
    </div>
  </div>
  <br>
  <div class="row">
    <div class=" col-lg-2 col-md-3">
    <%if user_signed_in? %>
      <table class="table table-bordered table-hover">
        <tbody>
          <tr>
            <% current_user.startups.each do |startups| %>
            <td>
              <%=link_to "My startup", startups, class:"text"  %>
            </td>
              <% end %>
          </tr>
          <tr>
            <% unless current_user.startups.any? %>
            <td><%=link_to "Add stratup", new_startup_path, class:"text-success"  %></td>
            <% end %>
         </tr>
          <tr>
            <td> <%= link_to 'Chat room', conversations_path, class:"text"%></td>
         </tr>
        <tr>
           <td><%= link_to 'Expand my network', users_path,class:"text" %></td>
        </tr>
      </tbody>
    </table>
  <% end %>
  </div>
  <div class="col-lg-10 col-md-9">
      <% @startups.each do |startup| %>
            <div class="row">
                <%= image_tag startup.banner_thumbnail, class:"img-fluid"%>
                <table class="table table-bordered">
                  <tbody>
                    <tr>
                      <td colspan="6"><%= startup.resume %></td>
                    </tr>
                    <tr>
                      <td><strong>Name</strong> : <%= startup.name %> </td>
                      <td><strong>Contact</strong> : <%= startup.contact %> </td>
                      <td><strong>adress</strong> : <%= startup.adresse %> </td>
                      <td><strong><%= startup.sector_of_business %></strong> startup  </td>
                      <td>
                      <strong><%=startup.favorites.count %></strong> <img src="/etoile.png" alt="contributeur (s)" width="25" height="25">
                      </td>
                      <td> <%= link_to 'show startup', startup,class:"btn btn-sm btn-success" %></td>
                    </tr>
                </tbody>
              </table>
            </div>
      <% end %>
    </div>
  </div>
  <%= paginate @startups %>
  <%= render 'startups/footer' %>
</div>

app/views/startups/new.html.erb
<div class="field">
  <%= render 'form' %>
  <hr>
    <small>Before adding a startup please read the terms of reference. adding a startup on the platform
    means that you have read and accepted the terms and conditions</small>
    <%= link_to 'LEAGLS TERMS', termes_path, class:"text-success" %>
</div>

app/views/startups/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-2 col-md-3">
      <table class="table table-bordered ">
        <tbody>
          <tr>
            <td><%= image_tag @startup.logo_thumbnail,style: 'width:100%;'%></td>
          </tr>
          <tr>
            <td>name: <strong><%= @startup.name %></td>
           </tr>
           <tr>
             <td><strong><%= @startup.sector_of_business %></strong> statup</td>
          </tr>
          <tr>
            <td class="bi bi-person-lines-fill"> contact : <strong><%= @startup.contact %></td>
           </tr>
            <tr>
              <td><i class="fas fa-map-marker-alt"></i><%= @startup.adresse %></td>
           </tr>
           <tr>
             <td> Addresse : <strong><%= @startup.adresse %> </strong></td>
          </tr>
           <tr>
             <td>
               <%= link_to "Owener profile", user_path(@startup.user.id), class:"btn btn-outline-info my-2 my-sm-0" %>
             </td>
           </tr>
      </tbody>
    </table>
    </div>
    <div class="offset-1 col-lg-9 col-md-7">
      <p><image controls width="100%" height="auto" src="<%= @startup.banner_thumbnail %>"></image></p>
        <hr>
        <p><%= @startup.resume %></p>
            <%= render 'favorites'%>
            <strong><%=@startup.favorites.count %></strong> <img src="/etoile.png" alt="contributeur (s)" width="25" height="25">
        <hr>
        <div class="embed-responsive embed-responsive-16by9">
          <%= get_video_iframe( @startup.video) %>
        </div>
        <hr>
        <% if user_signed_in? && current_user.id == @startup.user_id %>
            <%= link_to 'edit Statut', edit_startup_path(@startup.id),class:"btn btn-sm btn-info" %>
            <%= link_to 'Delete Startup', startup_path(@startup.id), method: :delete, data: { confirm: 'Are you sure?'},class:"btn btn-sm btn-danger" %>
        <% end %>
        <hr>
        <div class="text-center">
          <h4 >Give your opinion</h4>
          <small>You can participate in the development of this startup's idea by <br>
            giving advice, remarks, and why not some good ideas to grow.</small>
            <hr>
            <%= render partial: 'comments/form', locals: { comment: @comment, startup: @startup } %>
          </div>
            <div id="comments_area">
                <%= render partial: 'comments/index', locals: { comments: @comments, startup: @startup } %>
            </div>
        </div>
      </div>
  </div>